name: flutter_application_1
description: "Currency list."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  dio: ^5.9.0
  currency_picker: ^2.0.21
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  talker_flutter: ^5.1.13
  talker_bloc_logger: ^5.1.13
  talker_dio_logger: ^5.1.13
  country_flags: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/